config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  get '/api_teryt/items',               to: 'api_teryt#items'
  get '/api_teryt/items/:id',           to: 'api_teryt#item_show'
  get '/api_teryt/provinces',           to: 'api_teryt#provinces'
  get '/api_teryt/provinces/:id',       to: 'api_teryt#province_show'
  get '/api_teryt/province_districts',  to: 'api_teryt#province_districts'
  get '/api_teryt/districts/:id',       to: 'api_teryt#district_show'
  get '/api_teryt/district_communes',   to: 'api_teryt#district_communes'
  get '/api_teryt/communes/:id',        to: 'api_teryt#commune_show'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :api_uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :versions, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_for_role', on: :collection # Displays users for showed role
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_for_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :organizations do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'ajax_load_proposals', on: :member
      get 'ajax_load_registers', on: :member
    end    

    scope ':service_type', constraints: { service_type: /[jpt]/ } do

      resources :proposal_candidates do
        resources :wizard, only: [:show, :update], controller: 'proposal_candidates/wizard_steps'
      end    

      resources :proposals do
        post 'datatables_index', on: :collection
        get 'edit_to_approved', on: :member
        patch 'update_to_approved', on: :member
        get 'edit_to_rejected', on: :member
        patch 'update_to_rejected', on: :member
        get 'edit_to_annuled', on: :member
        patch 'update_to_annuled', on: :member
      end    

      resources :registers do
        get 'select2_index', on: :collection
        post 'datatables_index', on: :collection
        get 'ajax_load_proposals', on: :member
      end    
    end    

    get 'datatables/lang'
    get 'static_pages/home'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  # resources :apidocs, only: [:index]
  resources :swagger, only: [:index]

  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :apidocs, only: [:index]
      # resources :swagger, only: [:index]
      
      get :token, controller: 'base_api'
      resources :organizations, only: [] do
        post 'cbo_new_data_service', on: :collection
      end

      namespace :dictionary do
        resources :address_ext_types, only: [:index, :show]
        resources :address_types, only: [:index, :show]
        resources :attachment_types, only: [:index, :show]
        resources :identifier_types, only: [:index, :show]
        resources :jst_legal_form_types, only: [:index, :show]
        resources :legal_form_types, only: [:index, :show]
        resources :network_types, only: [:index, :show]
        resources :proposal_statuses, only: [:index, :show]
        resources :proposal_types, only: [:index, :show]
        resources :register_statuses, only: [:index, :show]
        resources :representative_types, only: [:index, :show]
        resources :service_types, only: [:index, :show]
      end

      scope ':service_type', constraints: { service_type: /[jpt]/ } do
        resources :registers, param: :id_or_number, only: [:index, :show]
        resources :proposals, only: [:create]
      end

    end

    namespace :v2 do
    end
  end
end

app/models/version.rb
class Version < PaperTrail::Version

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index, :datatables_index_trackable, :datatables_index_user]


  def index
    authorize :version, :index?
  end

  def datatables_index
    respond_to do |format|
      format.json{ render json: VersionDatatable.new(params, view_context: view_context) }
    end
  end

  def datatables_index_trackable
    respond_to do |format|
      format.json{ render json: VersionDatatable.new(params, view_context: view_context, trackable_id: params[:trackable_id], trackable_type: params[:trackable_type] ) }
    end
  end

  def datatables_index_user
    respond_to do |format|
      format.json{ render json: VersionDatatable.new(params, { only_for_current_user_id: params[:user_id] }) }
    end
  end

end

app/helpers/versions_helper.rb
module VersionsHelper

  ICON = "history"

  def version_icon_legend
    fa_icon(ICON)
  end

  def version_index_legend
    fa_icon(ICON, text: t("versions.index.title"))
  end

end

app/views/versions/_versions_tab.html.erb
<div id="tab_versions">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %>&nbsp;&nbsp;-&nbsp;&nbsp;<%=  version_index_legend %></legend>

    <div class="row">
      <div class="col-sm-12">
        <table id="trackable-versions" class="hover cell-border compact" width="100%" 
          data-source="<%= datatables_index_trackable_versions_path(trackable_id: trackable_id, trackable_type: trackable_type, format: :json) %>",
          data-locale_url="<%= datatables_lang_path(format: :json) %>">         
          <thead>
            <tr>
            <th><%= Version.human_attribute_name(:id) %></th>
            <th><%= Version.human_attribute_name(:created_at) %></th>
            <th><%= Version.human_attribute_name(:transaction_id) %></th>
            <th><%= Version.human_attribute_name(:created_by) %></th>
            <th><%= Version.human_attribute_name(:event) %></th>
            <th><%= Version.human_attribute_name(:trackable_type) %></th>
            <th><%= Version.human_attribute_name(:trackable_id) %></th>
            <!-- <th><%#= Version.human_attribute_name(:item_subtype) %></th> -->
            <th><%= Version.human_attribute_name(:object_changes) %></th>
            <th><%= Version.human_attribute_name(:parameters) %></th>
            </tr>
          </thead>

          <tbody>                    
            <!--data from JSON -->
          </tbody>

        </table>
      </div>
    </div>

  </fieldset>
</div>

app/views/versions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h3 class="center colored-title index-title"><%= version_index_legend %></h3>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <table id="versions-table" class="hover cell-border" cellspacing="0" width="100%" 
        data-source="<%= datatables_index_versions_path(format: :json) %>",
        data-locale_url="<%= datatables_lang_path(format: :json) %>">
        <thead>
          <tr>
            <th><%= Version.human_attribute_name(:id) %></th>
            <th><%= Version.human_attribute_name(:created_at) %></th>
            <th><%= Version.human_attribute_name(:transaction_id) %></th>
            <th><%= Version.human_attribute_name(:created_by) %></th>
            <th><%= Version.human_attribute_name(:event) %></th>
            <th><%= Version.human_attribute_name(:trackable_type) %></th>
            <th><%= Version.human_attribute_name(:trackable_id) %></th>
            <!-- <th><%#= Version.human_attribute_name(:item_subtype) %></th> -->
            <th><%= Version.human_attribute_name(:object_changes) %></th>
            <th><%= Version.human_attribute_name(:parameters) %></th>
          </tr>
        </thead>

        <tbody>
           <!--data from JSON -->
        </tbody>
      </table>
    </div> <!--/col-sm-12 -->
  </div> <!--/row -->
</div> <!--/container -->