config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  get '/api_teryt/items',               to: 'api_teryt#items'
  get '/api_teryt/items/:id',           to: 'api_teryt#item_show'
  get '/api_teryt/provinces',           to: 'api_teryt#provinces'
  get '/api_teryt/provinces/:id',       to: 'api_teryt#province_show'
  get '/api_teryt/province_districts',  to: 'api_teryt#province_districts'
  get '/api_teryt/districts/:id',       to: 'api_teryt#district_show'
  get '/api_teryt/district_communes',   to: 'api_teryt#district_communes'
  get '/api_teryt/communes/:id',        to: 'api_teryt#commune_show'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :api_uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :versions, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_for_role', on: :collection # Displays users for showed role
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_for_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :organizations do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'ajax_load_proposals', on: :member
      get 'ajax_load_registers', on: :member
    end    

    scope ':service_type', constraints: { service_type: /[jpt]/ } do

      resources :proposal_candidates do
        resources :wizard, only: [:show, :update], controller: 'proposal_candidates/wizard_steps'
      end    

      resources :proposals do
        post 'datatables_index', on: :collection
        get 'edit_to_approved', on: :member
        patch 'update_to_approved', on: :member
        get 'edit_to_rejected', on: :member
        patch 'update_to_rejected', on: :member
        get 'edit_to_annuled', on: :member
        patch 'update_to_annuled', on: :member
      end    

      resources :registers do
        get 'select2_index', on: :collection
        post 'datatables_index', on: :collection
        get 'ajax_load_proposals', on: :member
      end    
    end    

    get 'datatables/lang'
    get 'static_pages/home'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  # resources :apidocs, only: [:index]
  resources :swagger, only: [:index]

  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :apidocs, only: [:index]
      # resources :swagger, only: [:index]
      
      get :token, controller: 'base_api'
      resources :organizations, only: [] do
        post 'cbo_new_data_service', on: :collection
      end

      namespace :dictionary do
        resources :address_ext_types, only: [:index, :show]
        resources :address_types, only: [:index, :show]
        resources :attachment_types, only: [:index, :show]
        resources :identifier_types, only: [:index, :show]
        resources :jst_legal_form_types, only: [:index, :show]
        resources :legal_form_types, only: [:index, :show]
        resources :network_types, only: [:index, :show]
        resources :proposal_statuses, only: [:index, :show]
        resources :proposal_types, only: [:index, :show]
        resources :register_statuses, only: [:index, :show]
        resources :representative_types, only: [:index, :show]
        resources :service_types, only: [:index, :show]
      end

      scope ':service_type', constraints: { service_type: /[jpt]/ } do
        resources :registers, param: :id_or_number, only: [:index, :show]
        resources :proposals, only: [:create]
      end

    end

    namespace :v2 do
    end
  end
end

app/models/proposal_type.rb
class ProposalType < ActiveRecord::Base

  PROPOSAL_TYPE_REGISTRATION = 1
  PROPOSAL_TYPE_CHANGE = 2
  PROPOSAL_TYPE_DELETION = 3
  PROPOSAL_TYPE_CERTIFICATE = 4

  PROPOSAL_TYPES = [ PROPOSAL_TYPE_REGISTRATION,
                     PROPOSAL_TYPE_CHANGE,
                     PROPOSAL_TYPE_DELETION,
                     PROPOSAL_TYPE_CERTIFICATE ]

  PROPOSAL_TYPES_PRESENCE_NETWORK_OR_SERVICE = [ PROPOSAL_TYPE_REGISTRATION,
                                                 PROPOSAL_TYPE_CHANGE ]

  PROPOSAL_TYPES_ENABLED_REGISTER_ID = [ PROPOSAL_TYPE_CHANGE,
                                         PROPOSAL_TYPE_DELETION,
                                         PROPOSAL_TYPE_CERTIFICATE ]

  # relations
  has_many :proposals, dependent: :nullify

  # validates
  validates :name, presence: true,
                    length: { in: 1..100 },
                    uniqueness: { case_sensitive: false }

end

app/controllers/api/v1/proposals_controller.rb
class Api::V1::ProposalsController < Api::V1::BaseApiController

  before_action :authenticate_system_param_basic
  # before_action :authenticate_system_param_token

  respond_to :json

  def create

    case params[:service_type]
    when 'j'
      prop_params = j_proposal_create_params
    when 't'
      prop_params = t_proposal_create_params
    else
      return render json: { code: 404, message: "Not found service_type: #{params[:service_type]}" }, status: :not_found
    end


    puts '-----------------------------------------------------------------------'
    # puts params
    puts 'prop_params:'
    puts prop_params
    puts '-----------------------------------------------------------------------'

            # proposal = Proposal.where(service_type: params[:service_type]).last
            # # render json: proposal, status: :created
            # render json: proposal, serializer: Api::V1::ProposalSerializer, include: "**", meta: {total_count: 1, service_type: params[:service_type]}, status: :created

    # render json: { code: 201, message: "succesfull recived for cbo_new_data_service: id:#{params[:id]}), typ:#{params[:typ]}, source:#{params[:source]}" }, status: :ok
    # render json: { code: 200, message: "succesfull recived for cbo_new_data_service: id:#{params[:id]}), typ:#{params[:typ]}, source:#{params[:source]}" }, status: :ok


    proposal = Proposal.new(prop_params)
    # must save with transaction with Registry because change Registry status ex. "deletion_pending"
    if proposal.save_and_change_register_status
      # render :show, status: :created, location: @proposal 
      render json: proposal, serializer: Api::V1::ProposalSerializer, include: "**", meta: {total_count: 1, service_type: params[:service_type]}, status: :created
    else
      # render json: proposal.errors, status: :unprocessable_entity
      render json: { code: 422, message: "#{proposal.errors.full_messages}" }, status: :unprocessable_entity
    end

  end  


  private
    # Never trust parameters from the scary internet, only allow the white list through.
    # def proposal_params
    #   defaults = { author_id: "#{current_user.id}", service_type: params[:service_type] }
    #   params.require(:proposal).permit(:proposal_type_id, :proposal_status_id, :organization_id, :insertion_date, 
    #     :jst_resolution_date, :jst_resolution_number,
    #     :jst_providing_networks, :jst_provision_telecom_services, :jst_provision_related_services, :jst_other_telecom_activities, 
    #     :activity_area_whole_poland, :scheduled_start_date, :scheduled_end_date, :status_comment, :note, :author_id, 
    #       proposal_networks_attributes: [:id, :network_type_id, :description, :_destroy],
    #       proposal_services_attributes: [:id, :service_type_id, :description, :only_wholesale, :only_resale, :_destroy],
    #       proposal_areas_attributes: [:id, :province_code, :province_name, :district_code, :district_name, :commune_code, :commune_name, :_destroy],
    #       proposal_attachments_attributes: [:id, :attachment_type_id, :attached_pdf_file, :_destroy]
    #     ).reverse_merge(defaults)
    # end

    def j_proposal_create_params
      # defaults = { author_id: "#{current_user.id}", service_type: params[:service_type] }
      defaults = {service_type: params[:service_type],
                  proposal_status_id: ProposalStatus::PROPOSAL_STATUS_CREATED, 
                  register_id: prepare_register(params.fetch(:proposal, {})), 
                  author_id: prepare_author(params.fetch(:proposal, {})) }
      params.require(:proposal).permit(:proposal_type_id, :organization_id, :register_id, :insertion_date, 
        :jst_resolution_date, :jst_resolution_number,
        :jst_providing_networks, :jst_provision_telecom_services, :jst_provision_related_services, :jst_other_telecom_activities, 
        :activity_area_whole_poland, :scheduled_start_date, :scheduled_end_date, :status_comment, :note, :author_id, 
          proposal_areas_attributes: [:id, :province_code, :province_name, :district_code, :district_name, :commune_code, :commune_name, :_destroy],
          proposal_attachments_attributes: [:id, :attachment_type_id, :attached_pdf_file, :_destroy]
        ).merge(defaults)
    end

    def t_proposal_create_params
      # defaults = { author_id: "#{current_user.id}", service_type: params[:service_type] }
      # params.require(:proposal).permit(:proposal_type_id, :proposal_status_id, :organization_id, :insertion_date, 
      #   :activity_area_whole_poland, :scheduled_start_date, :scheduled_end_date, :status_comment, :note, :author_id, 
      #     proposal_networks_attributes: [:id, :network_type_id, :description, :_destroy],
      #     proposal_services_attributes: [:id, :service_type_id, :description, :only_wholesale, :only_resale, :_destroy],
      #     proposal_areas_attributes: [:id, :province_code, :province_name, :district_code, :district_name, :commune_code, :commune_name, :_destroy],
      #     proposal_attachments_attributes: [:id, :attachment_type_id, :attached_pdf_file, :_destroy]
      #   ).reverse_merge(defaults)
    end

    def prepare_author(proposal_params)
      @api_user = User.order(:created_at).first
      PaperTrail.request.whodunnit = @api_user.id

      param_author_id = proposal_params.fetch(:author_id, nil)
      if param_author_id.present?
        user = User.find_by(email: param_author_id) 
        user = User.create(email: param_author_id, author: @api_user) unless user.present?

        if user.present?
          @api_user = user
          PaperTrail.request.whodunnit = @api_user.id
          return @api_user.id
        else
          return nil
        end
      end 
    end

    def prepare_register(proposal_params)
      (proposal_params.fetch(:proposal_type_id) == ProposalType::PROPOSAL_TYPE_REGISTRATION) ?  nil : proposal_params.fetch(:register_id)
    end

end

app/controllers/api/v1/swagger/controllers/proposals_controller.rb
# frozen_string_literal: true

class Api::V1::Swagger::Controllers::ProposalsController
  include Swagger::Blocks

  swagger_path '/j/proposals' do
    operation :post do
      key :description, 'Creates a new JST proposal'
      key :tags, [
        'Proposal'
      ]

      security do
        key :BasicAuth, []
      end

      parameter do
        key :name, :j_proposal
        key :in, :body
        key :description, 'data of the new JST proposal'
        key :required, true
        schema do
          key :'$ref', :JProposalInput
        end
      end

      response 201 do
        key :description, 'Proposal JST created'
        schema do
          property :data do
            key :'$ref', :JProposal
          end

          # property :meta do
          #   key :'$ref', :Meta
          # end
        end
      end

      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end

    end
  end

  #--------------------------------------

  swagger_path '/t/proposals' do
    operation :post do
      key :description, 'Creates a new PT proposal'
      key :tags, [
        'Proposal'
      ]

      security do
        key :BasicAuth, []
      end

      parameter do
        key :name, :t_proposal
        key :in, :body
        key :description, 'data of the new PT proposal'
        key :required, true
        schema do
          key :'$ref', :TProposalInput
        end
      end

      response 201 do
        key :description, 'Proposal PT created'
        schema do
          property :data do
            key :'$ref', :TProposal
          end

          # property :meta do
          #   key :'$ref', :Meta
          # end
        end
      end

      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end

    end
  end


end

app/controllers/api/v1/swagger/models/proposal.rb
module Api::V1::Swagger::Models::Proposal
  include Swagger::Blocks

  swagger_schema :JProposal do
    key :type, :object
    key :required, %i[id proposal_type_id insertion_date jst_resolution_date jst_resolution_number jst_providing_networks jst_provision_telecom_services jst_provision_related_services jst_other_telecom_activities activity_area_whole_poland scheduled_start_date scheduled_end_date author_id]

    property :id do
      key :type, :integer
      key :format, :int64
    end

    property :email do
      key :type, :string
    end

    property :created_at do
      key :type, :string
      key :format, 'date-time'
    end

    property :updated_at do
      key :type, :string
      key :format, 'date-time'
    end
  end


  swagger_schema :TProposal do
    key :type, :object
    key :required, %i[id2 email2 created_at2]

    property :id2 do
      key :type, :integer
      key :format, :int64
    end

    property :email2 do
      key :type, :string
    end

    property :created_at2 do
      key :type, :string
      key :format, 'date-time'
    end

  end


end

app/controllers/api/v1/swagger/models/proposal_type.rb
module Api::V1::Swagger::Models::ProposalType
# class Api::V1::Swagger::Models::ProposalType < ActiveRecord::Base
  include Swagger::Blocks

  swagger_schema :ProposalType do
    key :required, [:id, :name]
    property :id do
      key :type, :integer
      key :format, :int64
    end
    property :name do
      key :type, :string
    end
  end

  # ...
end

app/helpers/proposals_helper.rb
module ProposalsHelper

  ICON = "file-contract"

  def proposal_icon_legend
    fa_icon(ICON)
  end

  def proposal_legend(service_type=nil)
    service_type.present? ? fa_icon(ICON, text: t("proposals_#{service_type}.show.title")) : fa_icon(ICON, text: t("proposals.show.title"))
  end

  def proposal_show_legend(service_type=nil)
    service_type.present? ? fa_icon(ICON, text: t("proposals_#{service_type}.show.title")) : fa_icon(ICON, text: t("proposals.show.title"))
  end

  def proposal_index_legend(service_type=nil)
    service_type.present? ? fa_icon(ICON, text: t("proposals_#{service_type}.index.title")) : fa_icon(ICON, text: t("proposals.index.title"))
  end

  def proposal_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("proposals_#{data_obj.service_type}.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def proposal_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("proposals.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def proposal_new_edit_legend(data_obj)
    data_obj.new_record? ? proposal_new_legend(data_obj) :  proposal_edit_legend(data_obj)
  end

  def proposal_info_legend(data_obj)
    proposal_show_legend(data_obj.service_type) + ": " + data_obj.fullname
  end

  def proposal_policy_check(proposal, action, service_type)
    unless ['j', 'p', 't'].include?(service_type)
       raise "Ruby injection register type"
    end
    unless ['index_in_role', 'index', 'show', 'new', 'create', 'edit', 'update', 'destroy', 'print', 'work', 'version',
            'edit_to_approved', 'edit_to_rejected', 'edit_to_annuled', 
            'update_to_approved', 'update_to_rejected', 'update_to_annuled'].include?(action)
       raise "Ruby injection action type"
    end
    return policy(proposal).send("#{action}_#{service_type}?")
  end
end

app/views/proposals/_data_1_basic.html.erb
<div class="row">

  <div class="form-group col-sm-12">
    <fieldset class="my-fieldset-short">
      <legend class="my-fieldset"><%= t('proposals.fieldset.proposal_basic_title') %></legend>

      <div class="row">
        <div class="form-group col-sm-3">
          <p><strong><%= Proposal.human_attribute_name(:insertion_date) %></strong></p>
          <%= formated_date(proposal.insertion_date) %>
        </div>

        <div class="form-group col-sm-3">
          <p><strong><%= Proposal.human_attribute_name(:proposal_type) %></strong></p>
          <%= proposal.proposal_type.name %>
        </div>

        <%if proposal.register.present?  %>
          <div class="form-group col-sm-3">
            <p><strong><%= Proposal.human_attribute_name(:register) %></strong></p>
            <%= link_to(proposal.register.fullname, register_path(proposal.service_type, proposal.register)) %>
          </div>
        <% end %>

        <div class="form-group col-sm-3">
          <p><strong><%= Proposal.human_attribute_name(:proposal_status) %></strong></p>
          <%= proposal.proposal_status.name %>
        </div>
      </div>

      <div class="row">
        <% if proposal.approved_date.present? %>
          <div class="form-group col-sm-3">
            <p><strong><%= Proposal.human_attribute_name(:approved_date) %></strong></p>
            <%= formated_date(proposal.approved_date) %>
          </div>
        <% end %>
        <% if proposal.rejected_date.present? %>
          <div class="form-group col-sm-3">
            <p><strong><%= Proposal.human_attribute_name(:rejected_date) %></strong></p>
            <%= formated_date(proposal.rejected_date) %>
          </div>
        <% end %>
        <% if proposal.annuled_date.present? %>
          <div class="form-group col-sm-3">
            <p><strong><%= Proposal.human_attribute_name(:annuled_date) %></strong></p>
            <%= formated_date(proposal.annuled_date) %>
          </div>
        <% end %>
      </div>

      <div class="row">
        <div class="form-group col-sm-12">
          <p><strong><%= Proposal.human_attribute_name(:organization) %></strong></p>
          <%= link_to(proposal.organization.fullname_with_nip, organization_path(proposal.organization)) %>
        </div>
      </div>

    </fieldset>
  </div>

</div>  <!-- /row -->

app/views/proposals/_data_2_j.html.erb
<div class="row">

  <div class="form-group col-sm-12">
    <fieldset class="my-fieldset-short">
      <legend class="my-fieldset"><%= t('proposals.fieldset.proposal_networks_title') %></legend>

      <div class="row">
        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_resolution_date) %></strong></p>
          <%= formated_date(proposal.jst_resolution_date) %>
        </div>

        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_resolution_number) %></strong></p>
          <%= proposal.jst_resolution_number %>
        </div>
      </div>

      <hr class="hr-without-margins">

      <div class="row">
        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_providing_networks) %></strong></p>
        </div>
        <div class="form-group col-sm-4">
          <%= t proposal.jst_providing_networks %>
        </div>
      </div> <!--/row -->

      <div class="row">
        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_provision_telecom_services) %></strong></p>
        </div>
        <div class="form-group col-sm-4">
          <%= t proposal.jst_provision_telecom_services %>
        </div>
      </div> <!--/row -->

      <div class="row">
        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_provision_related_services) %></strong></p>
        </div>
        <div class="form-group col-sm-4">
          <%= t proposal.jst_provision_related_services %>
        </div>
      </div> <!--/row -->

      <div class="row">
        <div class="form-group col-sm-4">
          <p><strong><%= Proposal.human_attribute_name(:jst_other_telecom_activities) %></strong></p>
        </div>
        <div class="form-group col-sm-4">
          <%= t proposal.jst_other_telecom_activities  %>
        </div>
      </div> <!--/row -->

    </fieldset>
  </div>

</div>  <!-- /row -->

app/views/proposals/_data_2_p.html.erb
<h2>/views/proposals/_data_p</h2>

app/views/proposals/_data_5_schedules.html.erb
<div class="row">

  <div class="form-group col-sm-12">
    <fieldset class="my-fieldset-short">
      <legend class="my-fieldset"><%= t('proposals.fieldset.proposal_scheduled_title') %></legend>

      <div class="row">

        <div class="form-group col-sm-3">
          <p><strong><%= Proposal.human_attribute_name(:scheduled_start_date) %></strong></p>
          <%= formated_date(proposal.scheduled_start_date) %>
        </div>

        <div class="form-group col-sm-3">
          <p><strong><%= Proposal.human_attribute_name(:scheduled_end_date) %></strong></p>
          <%= formated_date(proposal.scheduled_end_date) %>
        </div>

      </div> <!--/row -->

    </fieldset>
  </div>

</div>  <!-- /row -->

app/views/proposals/_form_2_p.html.erb
<h2>/views/proposals/_form_p</h2>

app/views/proposals/_form_7_status_comment.html.erb
<div class="row">

  <div class="col-sm-6">

    <div class="row">
      <div class="form-group col-sm-12">
        <%= f.label :status_comment, class: 'control-label' %>
        <%= f.trix_editor :status_comment %>
        <%#= f.text_area :status_comment, :rows => 4, class: 'form-control input-sm' %>
      </div>
    </div>  <!-- /row -->          

  </div> <!--/col-sm-6-->

</div>

app/views/proposals/_form_p.html.erb
<h2>/views/proposals/_form_p</h2>

app/views/proposals/_form_to_annuled.html.erb
<div class="row">
  <div class="col-sm-12">

    <%= form_with(model: proposal, url: { action: 'update_to_annuled' , service_type: params[:service_type] }, local: true) do |f| %>

      <% input_disabled ||= false %>

      <%= form_errors_for proposal %>

      <div class="row">
        <div class="col-sm-12">

          <div class="alert alert-warning" role="alert">
            <p class="center"><strong><%= t("helpers.links.proposal_to_annuled") %></strong></p>
          </div>

        </div>
      </div>

      <%= render "data_1_basic", proposal: proposal %>

      <hr>

      <div class="row">
        <div class="col-sm-6">

          <div class="row">
            <div class="form-group required col-sm-4">
              <%= f.label :annuled_date, class: 'control-label' %>
              <%= f.text_field :annuled_date, class: 'form-control input-sm datepicker', disabled: false %>
            </div>
          </div>  <!-- /row -->
          <div class="row">
            <div class="form-group required col-sm-12">
              <%= f.label :status_comment, class: 'control-label' %>
              <%= f.trix_editor :status_comment %>
              <%#= f.text_area :note, :rows => 4, class: 'form-control input-sm' %>
            </div>
          </div>  <!-- /row -->

        </div>  <!-- /col-sm-7 -->

        <div class="col-sm-6">

          <div class="row">
            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
              <%#= f.text_area :note, :rows => 4, class: 'form-control input-sm' %>
            </div>
          </div>  <!-- /row -->
          
        </div>  <!-- /col-sm-5 -->
      </div>  <!-- /row -->

      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to proposal_path(proposal.service_type, proposal), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>

          <%= f.submit nil, data: { confirm: t('helpers.links.confirm_to_annuled', data: proposal.fullname) }, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->
      
    <% end %>

  </div> <!--/col-sm-12-->
</div>

app/views/proposals/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= proposal_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to proposals_path(params[:service_type]), title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= proposal_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">


      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to proposals_path(params[:service_type]), title: t('.index'), rel: 'tooltip' do %>
            <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>


    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/proposals/edit.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= proposal_edit_legend(@proposal) %></legend>
            <%= render 'form', proposal: @proposal %>
          </fieldset>
        </div>
      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/proposals/edit_to_annuled.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= proposal_edit_legend(@proposal) %></legend>

            <%= render 'form_to_annuled', proposal: @proposal %>

          </fieldset>
        </div>
      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 

app/views/proposals/edit_to_approved.html.erb
<div class="grid-container">

  <div class="sidebar">
    <%= render 'sidebar_edit' %>
  </div>

  <div class="main-content">
    <br>
    <div class="container-fluid"> 
      <div class="row">
        <div class="col-sm-12">
          <fieldset class="my-fieldset">
            <legend class="my-fieldset colored-title"><%= proposal_edit_legend(@proposal) %></legend>

            <%= render 'form_to_approved', proposal: @proposal %>

          </fieldset>
        </div>
      </div>

    </div> <!--/container-fluid--> 
  </div> <!--/main-content--> 

</div> <!--/grid-containe--> 