config/routes.rb
Rails.application.routes.draw do

#          new_user_session GET      /users/saml/sign_in(.:format)                       devise/saml_sessions#new
#              user_session POST     /users/saml/auth(.:format)                          devise/saml_sessions#create
#      destroy_user_session DELETE   /users/sign_out(.:format)                           devise/saml_sessions#destroy
#     metadata_user_session GET      /users/saml/metadata(.:format)                      devise/saml_sessions#metadata
# idp_sign_out_user_session GET|POST /users/saml/idp_sign_out(.:format)                  devise/saml_sessions#idp_sign_out


  devise_for :users, controllers: {
    saml_sessions: 'users/saml_sessions'
  }

  get '/api_teryt/items',               to: 'api_teryt#items'
  get '/api_teryt/items/:id',           to: 'api_teryt#item_show'
  get '/api_teryt/provinces',           to: 'api_teryt#provinces'
  get '/api_teryt/provinces/:id',       to: 'api_teryt#province_show'
  get '/api_teryt/province_districts',  to: 'api_teryt#province_districts'
  get '/api_teryt/districts/:id',       to: 'api_teryt#district_show'
  get '/api_teryt/district_communes',   to: 'api_teryt#district_communes'
  get '/api_teryt/communes/:id',        to: 'api_teryt#commune_show'

  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

    resources :api_uke_regulations, only: [:index]

    resources :works, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :versions, only: [:index] do
      post 'datatables_index', on: :collection # for User
      post 'datatables_index_trackable', on: :collection # for Trackable
      post 'datatables_index_user', on: :collection # for User
    end

    resources :users do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'datatables_index_for_role', on: :collection # Displays users for showed role
    end

    resources :roles do
      post 'datatables_index', on: :collection
      get 'datatables_index_for_user', on: :collection # Displays roles for showed user
      resources :users, only: [:create, :destroy], controller: 'roles/users'
    end    

    resources :organizations do
      get 'select2_index', on: :collection
      post 'datatables_index', on: :collection
      get 'ajax_load_proposals', on: :member
      get 'ajax_load_registers', on: :member
    end    

    scope ':service_type', constraints: { service_type: /[jpt]/ } do

      resources :proposal_candidates do
        resources :wizard, only: [:show, :update], controller: 'proposal_candidates/wizard_steps'
      end    

      resources :proposals do
        post 'datatables_index', on: :collection
        get 'edit_to_approved', on: :member
        patch 'update_to_approved', on: :member
        get 'edit_to_rejected', on: :member
        patch 'update_to_rejected', on: :member
        get 'edit_to_annuled', on: :member
        patch 'update_to_annuled', on: :member
      end    

      resources :registers do
        get 'select2_index', on: :collection
        post 'datatables_index', on: :collection
        get 'ajax_load_proposals', on: :member
      end    
    end    

    get 'datatables/lang'
    get 'static_pages/home'

    root to: 'static_pages#home'
	end

  root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root
  # get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302),
  #               constraints: { path: /(?!(#{I18n.available_locales.join("|")})\/).*/ },
  #               format: false


  # resources :apidocs, only: [:index]
  resources :swagger, only: [:index]

  namespace :api, defaults: { format: :json } do
    require 'api_constraints'
    namespace :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :apidocs, only: [:index]
      # resources :swagger, only: [:index]
      
      get :token, controller: 'base_api'
      resources :organizations, only: [] do
        post 'cbo_new_data_service', on: :collection
      end

      namespace :dictionary do
        resources :address_ext_types, only: [:index, :show]
        resources :address_types, only: [:index, :show]
        resources :attachment_types, only: [:index, :show]
        resources :identifier_types, only: [:index, :show]
        resources :jst_legal_form_types, only: [:index, :show]
        resources :legal_form_types, only: [:index, :show]
        resources :network_types, only: [:index, :show]
        resources :proposal_statuses, only: [:index, :show]
        resources :proposal_types, only: [:index, :show]
        resources :register_statuses, only: [:index, :show]
        resources :representative_types, only: [:index, :show]
        resources :service_types, only: [:index, :show]
      end

      scope ':service_type', constraints: { service_type: /[jpt]/ } do
        resources :registers, param: :id_or_number, only: [:index, :show]
        resources :proposals, only: [:create]
      end

    end

    namespace :v2 do
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::BaseApiController

  before_action :authenticate_system_param_basic
  # before_action :authenticate_system_param_token

  respond_to :json

  def cbo_new_data_service
    # render json: { message: "succesfull recived for cbo_new_data_service: id:#{params[:id]}), typ:#{params[:typ]}, source:#{params[:source]}" }, status: :ok
    render json: { code: 200, message: "succesfull recived for cbo_new_data_service: id:#{params[:id]}), typ:#{params[:typ]}, source:#{params[:source]}" }, status: :ok
 end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:organization_status_id, :not_approved_comment )
    end

end

app/controllers/api/v1/swagger/controllers/organizations_controller.rb
# frozen_string_literal: true

class Api::V1::Swagger::Controllers::OrganizationsController
  include Swagger::Blocks

  swagger_path '/organizations/cbo_new_data_service' do
    operation :post do
      key :description, 'Push info for new CBO data'
      key :tags, [
        'Organization'
      ]

      security do
        key :BasicAuth, []
      end

      parameter do
        key :name, :null
        key :in, :body
        key :description, 'CBO message data'
        key :required, true
        schema do
          key :'$ref', :CboInput
        end
      end

      response 200 do
        key :description, 'Message received'
        schema do
          property :data do
            key :'$ref', :Cbo
          end

          # property :meta do
          #   key :'$ref', :Meta
          # end
        end
      end

      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end

    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized, except: [:index, :datatables_index, :ajax_load_proposals, :ajax_load_registers]
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :ajax_load_proposals, :ajax_load_registers]

  def ajax_load_proposals
    @proposals = @organization.proposals.joins(:proposal_type, :proposal_status, :organization)
                  .references(:proposal_type, :proposal_status).where(service_type: params[:service_type]).all
    respond_to do |format|
      # format.js  { render status: :ok, file: '/organizations/ajax_load_proposals.js.erb' }
      format.js  { render "ajax_load_proposals_#{params[:service_type]}", status: :ok }
    end 
  end

  def ajax_load_registers
    @registers = @organization.registers.joins(:register_status, :organization)
                  .references(:register_status).where(service_type: params[:service_type]).all
    respond_to do |format|
      format.js  { render "ajax_load_registers_#{params[:service_type]}", status: :ok }
    end 
  end

  def datatables_index
    respond_to do |format|
      format.json { render json: OrganizationDatatable.new(params, view_context: view_context ), serializer: nil }
      # without [active_model_serializers]:
      # format.json { render json: OrganizationDatatable.new(params, view_context: view_context ).to_json } 
    end
  end

  def index
    authorize :organization, :index?
    respond_to do |format|
      # disable button all/my if current_user not have role organization:index
      # format.html { render :index, locals: {index_in_role: policy(:organization).index_in_role?} }
      format.html { render :index }
    end
  end

  def select2_index
    authorize :organization, :index?
    params[:q] = params[:q]
    @organizations = Organization.includes(:features, :addresses).references(:features, :addresses)
      .order(:name).finder_organization(params[:q])
    @organizations_on_page = @organizations.page(params[:page]).per(params[:page_limit])
    
    render json: { 
      organizations: @organizations_on_page.as_json(methods: :fullname, only: [:id, :fullname, :name, :nip, :jointly_identifiers],
          include: {
            feature_identifiers: {only: [:id, :feature_value],
              include: { 
                feature_type: {only: [:id, :name]}
              }
            },
            addresses: {except: [:address_type_id, :addressable_type, :addressable_id],
              include: { 
                address_type: {only: [:id, :name]}
              }
            }
          }
        ),
      meta: { total_count: @organizations.count }  
    } 
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    authorize @organization, :show?

    respond_to do |format|
      format.html { render :show }
      format.json {
        render json: JSON.parse(@organization.to_json(methods: :fullname, only: [:id, :fullname, :name, :nip, :jointly_identifiers],
            include: {
              feature_identifiers: {only: [:id, :feature_value],
                include: { 
                  feature_type: {only: [:id, :name]}
                }
              },
              feature_address_exts: {only: [:id, :feature_value],
                include: { 
                  feature_type: {only: [:id, :name]}
                }
              },
              addresses: {except: [:address_type_id, :addressable_type, :addressable_id],
                include: { 
                  address_type: {only: [:id, :name]}
                }
              },
              representatives: {except: [:organization_id, :representative_type_id],
                include: {
                  features: {only: [:id, :feature_value],
                    include: { 
                      feature_type: {only: [:id, :name]}
                    }
                  },
                  addresses: {except: [:address_type_id, :addressable_type, :addressable_id],
                    include: { 
                      address_type: {only: [:id, :name]}
                    }
                  }
                }
              }
            }
          ))
      } 
    end
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @organization.name = params[:organization][:name].strip if params.dig(:organization, :name).present? 
    @organization.author = current_user
    authorize @organization, :new?
  end

  # GET /organizations/1/edit
  def edit
    authorize @organization, :edit?
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    authorize @organization, :create?
    respond_to do |format|
      if @organization.save
        @organization.log_work('create', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.created', data: @organization.fullname)
          redirect_to @organization 
        }
        format.json { render :show, status: :created, location: @organization }
        format.js { render :create }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    authorize @organization, :update?
    respond_to do |format|
      if @organization.update(organization_params)
        @organization.log_work('update', current_user.id)
        format.html { 
          flash[:success] = t('activerecord.successfull.messages.updated', data: @organization.fullname)
          redirect_to @organization 
        }
        format.json { render :show, status: :ok, location: @organization }
        format.js { render :update }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    authorize @organization, :destroy?
    destroyed_clone = @organization.clone
    if @organization.destroy
      destroyed_clone.log_work('destroy', current_user.id)
      flash[:success] = t('activerecord.successfull.messages.destroyed', data: @organization.fullname)
      redirect_to organizations_url
    else 
      flash.now[:error] = t('activerecord.errors.messages.destroyed', data: @organization.fullname)
      #redirect_to :back
      render :show
    end      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      defaults = { author_id: "#{current_user.id}" }
      params.require(:organization).permit(:name, :legal_form_type_id, :jst_legal_form_type_id, :jst_teryt, :nip, :note, :author_id,
        features_attributes: [:id, :feature_type_id, :feature_value, :_destroy],
        addresses_attributes: [ :id, :address_type_id, :country_code, :address_combine_id, 
          :province_code, :province_name, :district_code, :district_name, :commune_code, :commune_name,
          :city_code, :city_name, :parent_city_code, :parent_city_name, :street_code, :street_name, :street_attribute,
          :address_house, :address_number, :address_postal_code, :_destroy],
        representatives_attributes: [ :id, :representative_type_id, :first_name, :last_name, :note, :_destroy, 
          features_attributes: [:id, :feature_type_id, :feature_value, :_destroy],
          addresses_attributes: [ :id, :address_type_id, :country_code, :address_combine_id, 
            :province_code, :province_name, :district_code, :district_name, :commune_code, :commune_name,
            :city_code, :city_name, :parent_city_code, :parent_city_name, :street_code, :street_name, :street_attribute,
            :address_house, :address_number, :address_postal_code, :_destroy]
          ]
        ).reverse_merge(defaults)
    end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper

  ICON = "industry"

  def organization_icon_legend
    fa_icon(ICON)
  end

  def organization_legend
    fa_icon(ICON, text: t("organizations.show.title"))
  end

  def organization_show_legend
    fa_icon(ICON, text: t("organizations.show.title"))
  end

  def organization_index_legend
    fa_icon(ICON, text: t("organizations.index.title"))
  end

  def organization_edit_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("organizations.edit.title") + ": " + data_obj.fullname_was) : fa_icon(ICON, text: t("helpers.links.edit") )
  end

  def organization_new_legend(data_obj=nil)
    data_obj.present? ? fa_icon(ICON, text: t("organizations.new.title") + ": " + data_obj.fullname) : fa_icon(ICON, text: t("helpers.links.new") )
  end

  def organization_new_edit_legend(data_obj)
    data_obj.new_record? ? organization_new_legend(data_obj) :  organization_edit_legend(data_obj)
  end

  def organization_info_legend(data_obj)
    organization_show_legend + ": " + data_obj.fullname
  end

end

app/views/organizations/_data.html.erb
<div id="tab_data">
  <fieldset class="my-fieldset">
    <legend class="my-fieldset colored-title"><%= subtitle %></legend>
    <div class="row">

      <div class="col-sm-12">

        <%= form_errors_for @organization %>

        <div class="row">
          <!-- left  -->
          <div class="col-sm-6">

            <div class="row">
              <div class="form-group col-sm-12">
                <p><strong><%= Organization.human_attribute_name(:name) %></strong></p>
                <%= @organization.name %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-sm-12">
                <p><strong><%= Organization.human_attribute_name(:legal_form_type) %></strong></p>
                <%= @organization.legal_form_type.name %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-sm-8">
<!--          <div class="form-group col-sm-8" data-toggle="popover_info" title="<%#= Organization.human_attribute_name(:jst_legal_form_type) %>" data-content="<%#= Organization.human_attribute_name(:jst_legal_form_type_popover_info) %>" data-placement= "top"> -->
                <p><strong><%= Organization.human_attribute_name(:jst_legal_form_type) %></strong></p>
                <%= @organization.jst_legal_form_type.name if @organization.jst_legal_form_type.present? %>
              </div>
              <div class="form-group col-sm-4">
                <p><strong><%= Organization.human_attribute_name(:jst_teryt) %></strong></p>
                <%= @organization.jst_teryt %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-sm-4">
                <p><strong><%= Organization.human_attribute_name(:nip) %></strong></p>
                <%= @organization.nip %>
              </div>
            </div>

            <!-- nested: -->
            <div class="row">
              <div class="form-group col-sm-6">
                <fieldset class="my-fieldset-short">
                  <legend class="my-fieldset"><%= t('organizations.fieldset.identifiers_title') %></legend>

                  <div class="row">
                    <div class="form-group col-sm-12">

                      <%= render partial: "features/feature", collection: @organization.features.feature_only_identifier_type.order(:feature_value), as: :feature %>

                    </div>
                  </div> <!--/row -->
                </fieldset>
              </div>

              <div class="form-group col-sm-6">
                <fieldset class="my-fieldset-short">
                  <legend class="my-fieldset"><%= t('organizations.fieldset.address_ext_title') %></legend>

                  <div class="row">
                    <div class="form-group col-sm-12">

                      <%= render partial: "features/feature", collection: @organization.features.feature_only_address_ext_type.order(:feature_value), as: :feature %>

                    </div>
                  </div> <!--/row -->
                </fieldset>
              </div>
            </div>

            <!-- nested: -->
            <div class="row">
              <div class="form-group col-sm-12">
                <fieldset class="my-fieldset-short">
                  <legend class="my-fieldset"><%= t('organizations.fieldset.addresses_title') %></legend>

                  <div class="row">
                    <div class="form-group col-sm-12">

                      <%= render partial: "addresses/address", collection: @organization.addresses %>
                      <%#= render @organization.addresses %>

                    </div>
                  </div> <!--/row -->
                </fieldset>
              </div>
            </div>  <!-- /row -->
            
            <div class="row">
              <div class="form-group col-sm-12">
                <% if @organization.note.html_safe.size > 0 %>
                  <blockquote>
                    <%= @organization.note.html_safe %>
                  </blockquote>
                <% end %>
              </div>
            </div>  <!-- /row -->

          </div>  <!-- /col-sm-6 -->


          <!-- rights  -->
          <div class="col-sm-6">

            <div class="row">
              <div class="form-group col-sm-12">
                <fieldset class="my-fieldset-short">
                  <legend class="my-fieldset"><%= t('organizations.fieldset.representatives_title') %></legend>

                  <div class="row">
                    <div class="form-group col-sm-12">

                      <%= render partial: "representatives/representative", collection: @organization.representatives %>
                      <%#= render @organization.representatives %>

                    </div>
                  </div> <!--/row -->
                </fieldset>
              </div>
            </div>  <!-- /row -->
            
          </div>  <!-- /col-sm-6 -->
        </div>  <!-- /row -->


        <hr class="hr-without-top-margin">

        <div class="row">
          <div class="col-sm-12">

            <% if policy(@organization).destroy? %>
              <%= link_to organization_path(@organization),
                                  method: :delete,
                                  data: { confirm: t('helpers.links.confirm_destroy', data: @organization.name) }, 
                                  class: "btn btn-danger" do %>
                <span class="fa fa-trash"></span>
                <%= t("helpers.links.destroy") %>
              <% end %>
            <% end %>

            <% if policy(@organization).edit? %>
              <%= link_to edit_organization_path(@organization), class: "btn btn-primary" do %>
                <span class="fa fa-edit"></span>
                <%= t("helpers.links.edit") %>
              <% end %>
            <% end %>

            <h6 class="pull-right"><%= last_updated_legend(@organization) %></h6>

          </div> <!--/col-sm-12 -->
        </div> <!-- /row -->

      </div> <!--/col-sm-12-->  

    </div>
  </fieldset>

</div>

app/views/organizations/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: organization, local: true) do |f| %>

      <% input_disabled ||= false %>

      <%= form_errors_for organization %>

      <div class="row">
        <!-- left  -->
        <div class="col-sm-6">

          <div class="row">
            <div class="form-group required col-sm-12">
              <%= f.label :name, class: 'control-label' %>
              <%= f.text_field :name, autofocus: true, class: 'form-control input-sm', disabled: input_disabled %>
            </div>
          </div>  <!-- /row -->

          <div class="row">
            <div class="form-group required col-sm-12">
              <%= f.label :legal_form_type_id, class: 'control-label' %>
              <%= f.select :legal_form_type_id, 
                    FeatureType.only_legal_form_type.order(:name).collect {|v| [ "#{v[:name]}", v[:id] ] },
                    { include_blank: false }, 
                    { autofocus: false, class: 'form-control input-sm', disabled: input_disabled } %>
            </div>
          </div>  <!-- /row -->

          <div class="row">
            <div class="form-group required col-sm-8">
<!--        <div class="form-group required col-sm-8"  data-toggle="popover_info" title="<%#= Organization.human_attribute_name(:jst_legal_form_type) %>" data-content="<%#= Organization.human_attribute_name(:jst_legal_form_type_popover_info) %>" data-placement= "top"> -->
              <%= f.label :jst_legal_form_type_id, class: 'control-label' %>
              <%= f.select :jst_legal_form_type_id, 
                    FeatureType.only_jst_legal_form_type.order(:name).collect {|v| [ "#{v[:name]}", v[:id] ] },
                    { include_blank: true }, 
                    { autofocus: false, class: 'form-control input-sm', disabled: input_disabled } %>
            </div>
            <div class="form-group col-sm-4">
              <%= f.label :jst_teryt, class: 'control-label' %>
              <%= f.text_field :jst_teryt, autofocus: false, class: 'form-control input-sm', disabled: input_disabled %>
            </div>
          </div>  <!-- /row -->

          <div class="row">
            <div class="form-group required col-sm-4">
              <%= f.label :nip, class: 'control-label' %>
              <%= f.text_field :nip, autofocus: false, class: 'form-control input-sm', disabled: input_disabled %>
            </div>
          </div>  <!-- /row -->

          <!-- nested: -->
          <div class="row">
            <div class="col-sm-12">
              <fieldset class="my-fieldset">
                <legend class="my-fieldset"><%= t('organizations.fieldset.identifiers_title') %></legend>

                <div class='organization_features_01 clearfix'>

                  <div class='organization_features_01-sub-form'>
                    <%= f.fields_for :features do |organization_identifier_form|  %>
                      <%= render 'features/feature_identifier_fields', f: organization_identifier_form if (FeatureType.only_identifier_type.ids.include?(organization_identifier_form.object.feature_type_id) ) %> 
                    <% end %>
                  </div>
                  <%= link_to_add_fields( t("helpers.links.link_to_add_fields_nested"), f, :features, 'features/feature_identifier_fields') %>

                </div>

              </fieldset>
            </div> <!--/col-sm-12 -->

            <div class="col-sm-12">
              <fieldset class="my-fieldset">
                <legend class="my-fieldset"><%= t('organizations.fieldset.address_ext_title') %></legend>

                <div class='organization_features_02 clearfix'>

                  <div class='organization_features_02-sub-form'>
                    <%= f.fields_for :features do |organization_address_ext_form|  %>
                      <%= render 'features/feature_address_ext_fields', f: organization_address_ext_form if (FeatureType.only_address_ext_type.ids.include?(organization_address_ext_form.object.feature_type_id) )%> 
                    <% end %>
                  </div>
                  <%= link_to_add_fields( t("helpers.links.link_to_add_fields_nested"), f, :features, 'features/feature_address_ext_fields') %>

                </div>

              </fieldset>
            </div>             
          </div>  <!-- /row -->

          <div class="row">
            <div class="col-sm-12">
              <fieldset class="my-fieldset">
                <legend class="my-fieldset"><%= t('organizations.fieldset.addresses_title') %></legend>

                <div class='organization_address clearfix'>

                  <div class='organization_address-sub-form'>
                    <%= f.fields_for :addresses do |organization_address_form|  %>
                      <%= render 'addresses/address_fields', f: organization_address_form %> 
                    <% end %>
                  </div>
                  <%= link_to_add_fields( t("helpers.links.link_to_add_fields_nested"), f, :addresses, 'addresses/address_fields') %>

                </div>

              </fieldset>
            </div> 
          </div>  <!-- /row -->

          <div class="row">
            <div class="form-group col-sm-12">
              <%= f.label :note, class: 'control-label' %>
              <%= f.trix_editor :note %>
              <%#= f.text_area :note, :rows => 4, class: 'form-control input-sm' %>
            </div>
          </div>  <!-- /row -->

        </div>  <!-- /col-sm-6 -->


        <!-- rights  -->
        <div class="col-sm-6">

          <div class="row">
            <div class="col-sm-12">
              <fieldset class="my-fieldset">
                <legend class="my-fieldset"><%= t('organizations.fieldset.representatives_title') %></legend>

                <div class='representatives_04 clearfix'>

                  <div class='representatives_04-sub-form'>
                    <%= f.fields_for :representatives do |representative_form|  %>
                      <%= render 'representatives/representative_fields', f: representative_form if (FeatureType.only_representative_type.ids.include?(representative_form.object.representative_type_id) )%> 
                    <% end %>
                  </div>
                  <%= link_to_add_fields( t("helpers.links.link_to_add_fields_nested"), f, :representatives, 'representatives/representative_fields') %>

                </div>

              </fieldset>
            </div> 
          </div>  <!-- /row -->
          
        </div>  <!-- /col-sm-6 -->
      </div>  <!-- /row -->







      <hr class="hr-without-top-margin">

      <div class="row">
        <div class="col-sm-12">

          <%= link_to organization.new_record? ? organizations_path() : organization_path(organization.id), class: "btn btn-default" do %>
            <%= back_from_new_or_edit_legend %>
          <% end %>

          <%= f.submit nil, class: 'btn btn-success' %>

        </div> <!--/col-sm-12 -->
      </div> <!-- /row -->
      
    <% end %>

  </div> <!--/col-sm-12-->
</div>


<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/organizations/_sidebar_edit.html.erb
<button class="sideber-button fa fa-chevron-right" onclick="changeSidebar(this)" title="<%=t('sidebar')%>" rel='tooltip'></button>

<div class="sidebar-content-small container-fluid">
  <div class="center"><%= organization_icon_legend %></div>
  <hr>

  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">

        <li role="presentation" class="brand-nav"><%= link_to organizations_path, title: t('.index'), rel: 'tooltip' do %>
          <span class="fa fa-list"></span>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

</div>    


<div class="sidebar-content-large hidden container-fluid">
  <div class="center"><%= organization_legend %></div>
  <hr>
  <div class="row">
    <div class="col-sm-12">

      <ul class="nav nav-pills brand-pills nav-stacked" role="tablist">
 
        <li role="presentation" class="brand-nav"><%= link_to organizations_path, title: t('.index'), rel: 'tooltip' do %>
          <%= back_to_index_legend %>
          <% end %>
        </li>

      </ul>

    </div>
  </div>

  <hr>
  <div class="row">
    <div class="col-sm-12">
      <div class="center"><%= fa_icon("edit", size: '2x') %></div>
      <h3 class="center"><%= t('helpers.links.edit') %></h3>
    </div>
  </div>


</div>

app/views/organizations/ajax_load_proposals_j.js.erb
//toastr['info']("organizations/ajax_load_proposals_j.js.erb");
$("#div_proposals_j").html("<%= j (render partial: 'proposals/proposal', collection: @proposals ) %>");

app/views/organizations/ajax_load_proposals_p.js.erb
//toastr['info']("organizations/ajax_load_proposals_p.js.erb");
$("#div_proposals_p").html("<%= j (render partial: 'proposals/proposal', collection: @proposals ) %>");

app/views/organizations/ajax_load_proposals_t.js.erb
//toastr['info']("organizations/ajax_load_proposals_t.js.erb");
$("#div_proposals_t").html("<%= j (render partial: 'proposals/proposal', collection: @proposals ) %>");